---
abstract: 'extensible authentication framework for Dancer2 apps'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-Auth-Extensible
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SaltedHash: '0'
  Dancer2: '0'
  Mock::Quick: '0'
  Test::More: '0'
  YAML: '0'
resources:
  bugtracker: https://github.com/racke/Dancer2-Plugin-Auth-Extensible/issues
  homepage: https://github.com/racke/Dancer2-Plugin-Auth-Extensible/
  repository: https://github.com/racke/Dancer2-Plugin-Auth-Extensible
version: '0.302'
